#%RAML 1.0
title: Chappted
version: 1
baseUri: https://chappted.herokuapp.com/api/v{version}
mediaType: application/json
types:
  Base:
    type: object
    properties:
      typeName: string
      identifier: string
  Error:
    type: object
    properties:
      pointer: string
      message: string
  Errors:
    type: Error[]
    minItems: 1
  Category:
    type: Base
    properties:
      name: string
  Challenge:
    type: Base
    properties:
      title: string
      description?: string
      password?: string
      hasPassword: boolean
      endTime?: datetime
      type:
        enum: [ tournament, season, open ]
      matchesCount: integer
      category: Base
resourceTypes:
  crud: !include resourceTypes/crud.raml
traits:
  filterable: !include traits/filterable.raml
  sortable: !include traits/sortable.raml
  paginatable: !include traits/paginatable.raml
  includable: !include traits/includable.raml
/challenges:
  displayName: Challenges
  type: [
    crud: {
      requestExample: {
          title: "FIFA 18 Season 1",
          description: "The winter challenge inside Jamit Labs.",
          password: "secret",
          endTime: "2019-10-02T15:00:00Z",
          type: "season",
          categoryId: "4"
      },
      responseExample: {
        title: "FIFA 18 Season 1",
        description: "The winter challenge inside Jamit Labs.",
        hasPassword: true,
        endTime: "2019-10-02T15:00:00Z",
        type: "season",
        category: { typeName: "Category", identifier: "47" }
      },
      filterableProperties: "title,endTime,type,categoryId",
      sortableProperties: "title,endTime,type,categoryId",
      includableRelations: "category"
    }
  ]
  post:
    responses:
      422:
        body:
          type: Errors
          example:
            - pointer: "title"
              message: "can't be empty"
            - pointer: "endTime"
              message: "must be in the future"
