#%RAML 1.0
title: Chappted
version: 1
baseUri: https://chappted.herokuapp.com/api/v{version}
mediaType: application/json

types: !include types/allTypes.raml

resourceTypes:
  crud: !include resourceTypes/crud.raml

traits:
  filterable: !include traits/filterable.raml
  sortable: !include traits/sortable.raml
  paginatable: !include traits/paginatable.raml
  includable: !include traits/includable.raml

/challenges:
  displayName: Challenges
  type: [
    crud: {
      filterableProperties: "title,endTime,type,categoryId",
      sortableProperties: "title,endTime,type,categoryId",
      includableRelations: "category"
    }
  ]
  post:
    responses:
      422:
        body:
          type: Errors
          example:
            - pointer: "title"
              message: "can't be empty"
            - pointer: "endTime"
              message: "must be in the future"
