# Helper Types
Base:
  type: object
  properties:
    typeName: string
    identifier: string
Error:
  type: object
  properties:
    pointer: string
    message: string
Errors:
  type: Error[]
  minItems: 1

# Models
Category:
  type: object
  properties:
    name: string
Challenge:
  type: object
  properties:
    title: string
    description?: string
    endTime?: datetime
    category: Base
    type:
      enum: [ tournament, season, open ]
ChallengeRequest:
  type: Challenge
  properties:
    password?: string
  example: !include ../examples/challengeRequest.raml
ChallengeResponse:
  type: [ Challenge, Base]
  properties:
    hasPassword: boolean
    matchesCount: integer
  example: !include ../examples/challengeResponse.raml
