Base:
  type: object
Error:
  type: object
  properties:
    pointer: string
    message: string
Errors:
  type: Error[]
  minItems: 1
ChallengeType:
  type: Base
  properties:
    name: string
    identifier: integer
ChallengeCategory:
  type: Base
  properties:
    name: string
    identifier: integer
Challenge:
  type: Base
  properties:
    title: string
    description?: string
    endTime?: datetime
    challengeType: ChallengeType
    challengeCategory: ChallengeCategory
ChallengeRequest:
  type: Challenge
  properties:
    password?: string
  example: !include ../examples/challengeRequest.raml
ChallengeResponse:
  type: Challenge
  properties:
    identifier: integer
    hasPassword: boolean
  example: !include ../examples/challengeResponse.raml
