# Helper Types
Base:
  type: object
  properties:
    typeName: string
    identifier: string
ChallengeParticipation:
  type: object
  properties:
    challenge: Challenge
    isAdmin: boolean
UserCategoryRanking:
  type: object
  properties:
    category: Category
    points: integer
ChallengeTeam:
  type: object
  properties:
    name: string
    challengeTeamRanking: ChallengeTeamRanking
    matchParticipation: MatchParticipation
MatchParticipation:
  type: object
  properties:
    points: integer
    match: Match[]
ChallengeTeamRanking:
  type: object
  properties:
    points: integer
Match:
  type: object
  properties:
Error:
  type: object
  properties:
    pointer: string
    message: string
Errors:
  type: Error[]
  minItems: 1

# Models
User:
  type: object
  properties:
    nickname: string
    email: string
    challengeTeam: ChallengeTeam[]
UserRequest:
  type: [ User, Base ]
  properties:
    password: string
    challengeParticipation?: ChallengeParticipation[]
    userCategoryRanking?: UserCategoryRanking[]
  example: !include ../examples/userRequest.raml
UserResponse:
  type: [ User, Base ]
  properties:
    identifier: string
    challengeParticipation?: ChallengeParticipation[]
    userCategoryRanking?: UserCategoryRanking[]
  example: !include ../examples/userResponse.raml
Category:
  type: object
  properties:
    name: string
Challenge:
  type: object
  properties:
    title: string
    description?: string
    endTime?: datetime
    category: Base
    match?: Match[]
    challengeTeam: ChallengeTeam[]
    challengeTeamRanking?: ChallengeTeamRanking[]
    type:
      enum: [ tournament, season, open ]
ChallengeRequest:
  type: Challenge
  properties:
    password?: string
  example: !include ../examples/challengeRequest.raml
ChallengeResponse:
  type: [ Challenge, Base ]
  properties:
    hasPassword: boolean
    matchesCount: integer
  example: !include ../examples/challengeResponse.raml
