#%RAML 1.0 ResourceType
usage: Use for readable and writable resources
description: The <<resourcePathName>> resource type
get:
  description: Fetch multiple <<resourcePathName>>
  is: [
    paginatable,
    filterable: { properties: <<filterableProperties>> },
    sortable: { properties: <<sortableProperties>> },
    includable: { relations: <<includableRelations>> }
  ]
  responses:
    200:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response[]
post:
  description: Create a new <<resourcePathName | !singularize>>
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Request
  responses:
    201:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response
/{identifier}:
  get:
    description: Fetch a specific <<resourcePathName | !singularize>>
    is: [ includable: { relations: <<includableRelations>> } ]
    responses:
      200:
        body:
          type: <<resourcePathName | !singularize | !uppercamelcase>>Response
  put:
    description: Update a specific <<resourcePathName | !singularize>>
    body:
      type: <<resourcePathName | !singularize | !uppercamelcase>>Request
    responses:
      200:
        body:
          type: <<resourcePathName | !singularize | !uppercamelcase>>Response
  delete:
    description: Delete a specific <<resourcePathName | !singularize>>
    responses:
      204:
