identifier: "15"
title: "FIFA 18 Season 1"
description: "The winter challenge inside Jamit Labs."
hasPassword: true
endTime: "2019-10-02T15:00:00Z"
challengeType: {name: "Season", identifier: "3"}
challengeCategory: { name: "Category", identifier: "47" }
