typeName: "User"
identifier: "1"
nickname: "Karl"
email: "karl@chappted.com"
challengeParticipation:
  - challenge: Challenge
    - typeName: "Challenge"
    - identifier: "12"
    - title: "FIFA 18 Season 1"
    - description: "The winter challenge inside Jamit Labs."
    - endTime: "2019-10-02T15:00:00Z"
    - category: !include categoryBase.raml
    - type: "season"
    - hasPassword: true
    - matchesCount: 15
  - isAdmin: "true"
userCategoryRanking:
  - name: "Tischtennis"
  - points: "47"
