#%RAML 1.0 Trait
usage: Use for endpoints with sortable fields
description: Some fields of the <<resourcePathName | !singularize>> are sortable
queryParameters:
    sort=<<properties>>?:
      type: string
      description: Sortable according to JLS:API.
